modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPLv3"

[[mods]]

modId="unenchanted" #mandatory
version="${file.jarVersion}" #mandatory
logoFile="icon.png" #optional
authors="Favouriteless" #optional
description='''
A simple mod for your unenchanting needs!
'''
